//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Common.Utils {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Common.Utils.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author with this id not found.
        /// </summary>
        public static string AuthorIdNotFound {
            get {
                return ResourceManager.GetString("AuthorIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book with the images can&apos;t be added.
        /// </summary>
        public static string BookCreationFailureError {
            get {
                return ResourceManager.GetString("BookCreationFailureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book with the images can&apos;t be deleted.
        /// </summary>
        public static string BookDeletionFailureError {
            get {
                return ResourceManager.GetString("BookDeletionFailureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book with this id not found.
        /// </summary>
        public static string BookIdNotFound {
            get {
                return ResourceManager.GetString("BookIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book with these images can&apos;t be updated.
        /// </summary>
        public static string BookUpdateFailureError {
            get {
                return ResourceManager.GetString("BookUpdateFailureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book with this ISBN already exists.
        /// </summary>
        public static string ExistingBookError {
            get {
                return ResourceManager.GetString("ExistingBookError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre with this name already exists.
        /// </summary>
        public static string ExistingGenreError {
            get {
                return ResourceManager.GetString("ExistingGenreError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User still not returned this book.
        /// </summary>
        public static string ExistingReservationError {
            get {
                return ResourceManager.GetString("ExistingReservationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review with this data is already exist.
        /// </summary>
        public static string ExistingReviewError {
            get {
                return ResourceManager.GetString("ExistingReviewError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this login already exists.
        /// </summary>
        public static string ExistingUserLoginError {
            get {
                return ResourceManager.GetString("ExistingUserLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre with this id not found.
        /// </summary>
        public static string GenreIdNotFound {
            get {
                return ResourceManager.GetString("GenreIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hashed password cannot be null!.
        /// </summary>
        public static string HashedPasswordError {
            get {
                return ResourceManager.GetString("HashedPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jwt settings not found.
        /// </summary>
        public static string JwtSettingsError {
            get {
                return ResourceManager.GetString("JwtSettingsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity not found.
        /// </summary>
        public static string NotFoundError {
            get {
                return ResourceManager.GetString("NotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be null!.
        /// </summary>
        public static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation with this id not found.
        /// </summary>
        public static string ReservationIdNotFound {
            get {
                return ResourceManager.GetString("ReservationIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unacceptable reservation status.
        /// </summary>
        public static string ReservationStatusBadRequestError {
            get {
                return ResourceManager.GetString("ReservationStatusBadRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review with this id not found.
        /// </summary>
        public static string ReviewIdNotFound {
            get {
                return ResourceManager.GetString("ReviewIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret key not found.
        /// </summary>
        public static string SecretKeyNotFoundError {
            get {
                return ResourceManager.GetString("SecretKeyNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with the photo can&apos;t be deleted .
        /// </summary>
        public static string UserDeletionFailureError {
            get {
                return ResourceManager.GetString("UserDeletionFailureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this id not found.
        /// </summary>
        public static string UserIdNotFound {
            get {
                return ResourceManager.GetString("UserIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this image can&apos;t be registered.
        /// </summary>
        public static string UserRegistrationFailureError {
            get {
                return ResourceManager.GetString("UserRegistrationFailureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this photo can&apos;t be updated.
        /// </summary>
        public static string UserUpdatingFailureError {
            get {
                return ResourceManager.GetString("UserUpdatingFailureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password.
        /// </summary>
        public static string WrongPasswordError {
            get {
                return ResourceManager.GetString("WrongPasswordError", resourceCulture);
            }
        }
    }
}
